export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const REQUEST_METAR = 'REQUEST_METAR'
export const REQUEST_METAR_SUCCESS = 'REQUEST_METAR_SUCCESS'
export const REQUEST_METAR_FAILURE = 'REQUEST_METAR_FAILURE'

export const FETCH_LOCATION = 'FETCH_LOCATION'
export const REQUEST_GEONAMES = 'REQUEST_GEONAMES'
export const REQUEST_GEONAMES_SUCCESS = 'REQUEST_GEONAMES_SUCCESS'
export const REQUEST_GEONAMES_FAILURE = 'REQUEST_GEONAMES_FAILURE'
