export const REQUEST_GEOLOCATION = 'REQUEST_GEOLOCATION'
export const REQUEST_GEOLOCATION_SUCCESS = 'REQUEST_GEOLOCATION_SUCCESS'
export const REQUEST_GEOLOCATION_FAILURE = 'REQUEST_GEOLOCATION_FAILURE'

export const ADD_METAR = 'ADD_METAR'
export const REMOVE_METAR = 'REMOVE_METAR'
export const REQUEST_METAR = 'REQUEST_METAR'
export const REQUEST_METAR_SUCCESS = 'REQUEST_METAR_SUCCESS'
export const REQUEST_METAR_FAILURE = 'REQUEST_METAR_FAILURE'
