export const REQUEST_WEATHER = 'REQUEST_WEATHER'
export const REQUEST_WEATHER_SUCCESS = 'REQUEST_WEATHER_SUCCESS'
export const REQUEST_WEATHER_FAILURE = 'REQUEST_WEATHER_FAILURE'

export const REQUEST_GEOLOCATION = 'REQUEST_GEOLOCATION'
export const REQUEST_GEOLOCATION_SUCCESS = 'REQUEST_GEOLOCATION_SUCCESS'
export const REQUEST_GEOLOCATION_FAILURE = 'REQUEST_GEOLOCATION_FAILURE'
